[project]
channels = ["conda-forge"]
name = "AML-homework"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
server = "jupyter server"
export = "pixi project export conda-environment > environment.yml" # Dont forget to format

[dependencies]
jupyter = ">=1.1.1,<2"
python = ">=3.12.10,<3.13"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.3,<4"
scipy = ">=1.15.2,<2"
numpy = ">=2.2.6,<3"
pyprojroot = ">=0.3.0,<0.4"
pandas = ">=2.2.3,<3"
icecream = ">=2.1.4,<3"
pytorch = ">=2.6.0,<3"
keras = ">=3.10.0,<4"
tqdm = ">=4.67.1,<5"
transformers = ">=4.52.3,<5"
torchvision = ">=0.21.0,<0.22"
lightning = ">=2.5.1.post0,<3"
torchinfo = ">=1.8.0,<2"
spacy = ">=3.8.6,<4"
torchmetrics = ">=1.7.1,<2"
datasets = ">=3.6.0,<4"
timm = ">=1.0.15,<2"

[environments]
dev = {features = ["dev"], no-default-feature = true}
gpu = {features = ["gpu"]}
download-models = {features = ["download-models"], no-default-feature = true}

[feature.gpu]
platforms = ["win-64"]
system-requirements = {cuda = "12"}

[feature.dev.dependencies]
ruff = ">=0.11.8,<0.12"
jupytext = "*"

[feature.dev.tasks]
format = "ruff format src/"

[feature.dev.tasks.to_jup]
cmd = "jupytext {{ file }} --to notebook"
args = ["file"]

[feature.dev.tasks.to_py]
cmd = "jupytext {{ file }} --to py:percent"
args = ["file"]

[pypi-dependencies]
visualkeras = ">=0.1.4, <0.2"
kagglehub = ">=0.3.12, <0.4"
torchviz = ">=0.0.3, <0.0.4"
huggingface-hub = ">=0.30.0"

[feature.gpu.dependencies]
pytorch-gpu = ">=2.6.0,<3"

[feature.download-models]
platforms = ["win-64"]

[feature.download-models.dependencies]
python = "*"
jupyter = ">=1.1.1,<2"
huggingface_hub = ">=0.31.2,<0.32"
pydot = ">=4.0.0,<5"

[feature.download-models.pypi-dependencies]
tensorflow = "*"
keras = ">=3"
torch = "*"
pyprojroot = ">=0.3.0, <0.4"
keras-hub = ">=0.20.0, <0.21"
visualkeras = ">=0.1.4, <0.2"
kagglehub = ">=0.3.12, <0.4"
huggingface-hub = "*"
