[project]
channels = ["conda-forge"]
name = "AML-homework"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
server = "jupyter server"
export = "pixi project export conda-environment > environment.yml"

[dependencies]
jupyter = ">=1.1.1,<2"
python = ">=3.13.3,<3.14"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.3,<4"
scipy = ">=1.15.2,<2"
numpy = ">=2.2.5,<3"
pyprojroot = ">=0.3.0,<0.4"
pandas = ">=2.2.3,<3"
icecream = ">=2.1.4,<3"
pytorch = ">=2.6.0,<3"
keras = ">=3.9.2,<4"
tqdm = ">=4.67.1,<5"

[environments]
dev = {features = ["dev"], no-default-feature = true}
gpu = {features = ["gpu"]}

[feature.gpu]
platforms = ["win-64"]
system-requirements = {cuda = "12"}

[feature.dev.dependencies]
ruff = ">=0.11.8,<0.12"
nbconvert = "*"

[feature.dev.tasks]
format = "ruff format src/"
to_py = "jupyter nbconvert --to script"

[pypi-dependencies]
visualkeras = ">=0.1.4, <0.2"

[feature.gpu.dependencies]
pytorch-gpu = ">=2.6.0,<3"
