[project]
channels = ["conda-forge"]
name = "AML-homework"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]
server = "jupyter server"
export = "pixi project export conda-environment > environment.yml"

[dependencies]
jupyter = ">=1.1.1,<2"
python = "*"
scikit-learn = ">=1.6.1,<2"
matplotlib = ">=3.10.3,<4"
scipy = ">=1.15.2,<2"
numpy = ">=2.2.5,<3"
pyprojroot = ">=0.3.0,<0.4"
pandas = ">=2.2.3,<3"
icecream = ">=2.1.4,<3"
pytorch = ">=2.6.0,<3"
keras = ">=3.9.2,<4"
tqdm = ">=4.67.1,<5"
transformers = ">=4.51.3,<5"
huggingface_hub = ">=0.31.2,<0.32"

[environments]
dev = {features = ["dev"], no-default-feature = true}
gpu = {features = ["gpu"]}
download-models = {features = ["download-models"], no-default-feature = true}

[feature.gpu]
platforms = ["win-64"]
system-requirements = {cuda = "12"}

[feature.dev.dependencies]
ruff = ">=0.11.8,<0.12"
nbconvert = "*"

[feature.dev.tasks]
format = "ruff format src/"
to_py = "jupyter nbconvert --to script"

[pypi-dependencies]
visualkeras = ">=0.1.4, <0.2"

[feature.gpu.dependencies]
pytorch-gpu = ">=2.6.0,<3"

[feature.download-models]
platforms = ["win-64"]

[feature.download-models.dependencies]
python = "*"
jupyter = ">=1.1.1,<2"
huggingface_hub = ">=0.31.2,<0.32"
pydot = ">=4.0.0,<5"

[feature.download-models.pypi-dependencies]
tensorflow = "*"
keras = ">=3"
torch = "*"
pyprojroot = ">=0.3.0, <0.4"
keras-hub = ">=0.20.0, <0.21"
visualkeras = ">=0.1.4, <0.2"
kagglehub = ">=0.3.12, <0.4"
huggingface-hub = "*"
